repos:
- repo: https://github.com/PyCQA/autoflake
  rev: v2.3.1
  hooks:
  - id: autoflake
    name: autoflake
    entry: autoflake --in-place --remove-all-unused-imports
    language: python
    files: \.py$
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.12.0"
  hooks:
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v4.0.0-alpha.8"
  hooks:
  - id: prettier
    types_or: [css, javascript]
- repo: local
  hooks:
  - id: rst
    name: rst
    entry: rst-lint --encoding utf-8
    files: ^(HISTORY.rst|README.rst)$
    language: python
    additional_dependencies: [pygments, restructuredtext_lint]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.1
  hooks:
  - id: mypy
    files: ^(src/|tests/)
    args: []
    additional_dependencies: [types-attrs]
