version: 2

build:
  image: latest

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
   version: 3.6
   install:
      - method: pip
        path: .

conda:
  environment: base_environment.yml


