version: 2

build:
  image: latest

python:
    version: 3.7
    install:
        -   method: pip
            path: .
        -   requirements: docs/requirements.txt

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
