language: python

env:
  matrix:
    - SCRIPT=lint
    - SCRIPT=tests

python:
  - "3.6"

install:
  # setup using Conda (http://conda.pydata.org/docs/travis.html)
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda info -a  # for debug reasons

  - conda create -n qmxgraph python=$TRAVIS_PYTHON_VERSION coveralls pytest-cov
  - conda env update -n qmxgraph
  - source activate qmxgraph
  - conda list  # for debug reasons

script:
  - scripts/run_travis_$SCRIPT.sh

after_success:
  - coveralls
