name: qmxgraph

dependencies:
    - python >=3.6

    - attrs >=17
    - colorama
    - flake8
    - invoke
    - jinja2
    - oop-ext
    - pip
    - pre-commit
    - pyqt

environment:
  PYTHONPATH:
    - {{ root }}/src
  MYPYPATH:
    - {{ root }}/src
