name: qmxgraph

dependencies:
    - python >=3.7

    - attrs >=17
    - colorama
    - flake8
    - invoke
    - jinja2
    - oop-ext
    - pip
    - pre-commit
    - pyqt =5.12

environment:
  PYTHONPATH:
    - {{ root }}/src
  MYPYPATH:
    - {{ root }}/src
