{% set TEST_QMXGRAPH = os.environ.get('TEST_QMXGRAPH', '0') != '0' %}
name: qmxgraph

dependencies:
    - python >=3.7

    - attrs >=17
    - colorama
    - flake8
    - invoke
    - jinja2
    - oop-ext
    - pip
    - pre-commit
    - pyqt >=5.12,<6.0
    - pyqtwebengine

environment:
  PYTHONPATH:
    - {{ root }}/src
    {% if TEST_QMXGRAPH %}
    - {{ root }}/tests
    {% endif %}
  MYPYPATH:
    - {{ root }}/src
