{% set TEST_QMXGRAPH = os.environ.get('TEST_QMXGRAPH', '0') != '0' %}
{% set PYTHON_VERSION = os.environ.get('PYTHON_VERSION', '3.6') %}

name: qmxgraph

includes:
  - {{ root }}/_base_environment.devenv.yml

environment:
  # Tip: Use `--driver <driver_name>` to change driver for a single run
  {% if TEST_QMXGRAPH %}
  PYTEST_ADDOPTS: --driver PhantomJS
  {% endif %}

dependencies:
  - python ={{ PYTHON_VERSION }}
  {% if "PYTHON_VERSION" in os.environ %}
  - importlib_resources =1.3
  - zipp =3.3
  {% endif %}

  {% if TEST_QMXGRAPH %}
  - cherrypy
  - hypothesis ==3.11.0
  - pytest-mock
  - pytest-qt
  - pytest-rerunfailures
  - pytest-selenium >=1,<2
  - pytest-timeout
  {% if sys.platform != 'win32' %}
  - pytest-xvfb
  {% endif %}

  {% endif %}
