name: qmxgraph

dependencies:
    - jinja2
    - pyqt==5.6
    - cherrypy
    - six
    - pytest-timeout
    - colorama
    - pip:
      - invoke==0.12.2
      - pytest-qt
      - pytest-selenium
      - pytest-mock
      - pytest-xdist
      - pytest-xvfb

