{% set TEST_QMXGRAPH = os.environ.get('TEST_QMXGRAPH', '0') != '0' %}
{% set PYTHON_VERSION = os.environ['PYTHON_VERSION'] %}

name: qmxgraph

includes:
  - {{ root }}/_base_environment.devenv.yml

environment:
  # Tip: Use `--driver <driver_name>` to change driver for a single run
  {% if TEST_QMXGRAPH %}
  PYTEST_ADDOPTS: --driver PhantomJS
  {% endif %}

dependencies:
  - python ={{ PYTHON_VERSION }}

  {% if TEST_QMXGRAPH %}
  - cherrypy
  - hypothesis =3.11
  - pytest-mock
  - pytest-qt
  - pytest-rerunfailures
  - pytest-selenium >=1,<2
  - pytest-timeout
  - typing-extensions <4.2.0  # [PYTHON_VERSION=="3.6"]
  # Pin importlib_resources due to #151.
  - importlib_resources <5.10
  - pytest-xvfb  # [linux]
  {% endif %}
