{% set TEST_QMXGRAPH = os.environ.get('TEST_QMXGRAPH', '0') != '0' %}
{% set PYTHON_VERSION = os.environ.get('PYTHON_VERSION', '3.10') %}

name: qmxgraph

includes:
  - {{ root }}/_base_environment.devenv.yml

environment:
  # Tip: Use `--driver <driver_name>` to change driver for a single run
  {% if TEST_QMXGRAPH %}
  PYTEST_ADDOPTS: --driver Chrome
  {% endif %}

dependencies:
  - python ={{ PYTHON_VERSION }}

  {% if TEST_QMXGRAPH %}
  - cherrypy >=18.0.0
  - pytest-mock
  - pytest-qt
  - pytest-rerunfailures
  - pytest-selenium >2
  - pytest-timeout
  # Recent selenium versions (>=4.10.0) are currently incompatible with pytest-selenium (some constructor changed argument list).
  - selenium >=4.0.0, <4.10.0
  {% if sys.platform != 'win32' %}
  - pytest-xvfb
  {% endif %}

  # Not really required to run the tests but are closely related.
  - coveralls
  - pytest-cov
  {% endif %}
