{% set CONDA_PY = os.environ.get('CONDA_PY', '27') %}

name: qmxgraph-py{{ CONDA_PY }}

environment:
# PhantomJS
# pros:
# * doesn't open a browser (i.e. known as headless)
# * as consequence, doesn't interfere with developer GUI
# * uses Webkit, same web browser engine used by Qt
#
# cons:
# * seems slower than Firefox driver
# * harder to debug (can't put a breakpoint and take a look at web driver's
#   browser, for instance)
#
# Firefox
# pros:
# * easier to debug (Firefox [and Chrome] already come with developer tools
#   builtin nowadays)
#
# cons:
# * pops up a Firefox instance for each test
# * it is not the same web browser engine as used by Qt
#
# Tip: Use `--driver <driver_name>` to change driver for a single run
  - PYTEST_ADDOPTS: --driver PhantomJS

dependencies:
    - python=={{ '2.7.12' if PY2 else '3.5.2' }}
    - mxgraph==3.5.1.4  # TODO fogo: private package, not sure if we can distribute on forge
    - jinja2==2.8
    - pyqt5==5.5.1+3  # TODO fogo: forge doesn't have qt5 yet
    - cherrypy==3.8.0
    - pytest-qt=2.1.0
    - pytest-selenium=1.2.1
    - pytest-mock=1.4.0
    - phantomjs==2.1.1
    - invoke==0.12.2
    - six==1.10.0
    - fix-and-check-env==1.0.0  # TODO fogo: this is ESSS stuff only, remove later!
