name: qmxgraph

dependencies:
    - attrs>=17
    - cherrypy
    - colorama
    - flake8
    - hypothesis==3.11.0
    - jinja2
    - pyqt>=5.6
    - pytest-timeout
    - six
    - pip:
      - invoke==0.12.2
      - pytest-mock
      - pytest-qt
      - pytest-rerunfailures
      - pytest-selenium
      - pytest-xdist
      - pytest-xvfb

