name: qmxgraph

dependencies:
    - attrs >=17
    - cherrypy
    - colorama
    - flake8
    - hypothesis ==3.11.0
    - invoke
    - jinja2
    - pyqt =5.6
    - pytest-mock
    - pytest-qt
    - pytest-selenium
    - pytest-timeout
    - pytest-xvfb
    - pip:
      - pytest-rerunfailures

