name: build

on:
  push:
    branches:
      - master

  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: browser-actions/setup-chrome@v2.2.0
    - uses: prefix-dev/setup-pixi@v0.11.0
      with:
        cache: true
    - name: Tests
      run: pixi run bash scripts/run_tests.sh
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: pixi run coveralls
