name: build

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        CONDA_PY: ["36", "37", "38", "39"]
        include:
          - CONDA_PY: "36"
            PYTHON_VERSION: "=3.6"
          - CONDA_PY: "37"
            PYTHON_VERSION: "=3.7"
          - CONDA_PY: "38"
            PYTHON_VERSION: "=3.8"
          - CONDA_PY: "39"
            PYTHON_VERSION: "=3.9"


    steps:
    - uses: actions/checkout@v2
    # We need to install Qt on the system otherwise tests in
    # tests/test_qt_js_integration.py crash.
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ''
        channels: conda-forge,esss
        channel-priority: true
    - name: Install
      env:
        CONDA_PY: ${{ matrix.CONDA_PY }}
        PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      run: |
        conda config --system --set always_yes yes --set changeps1 no
        conda install -c conda-forge conda-devenv
        conda info -a
        export TEST_QMXGRAPH=1
        echo "=== conda devenv -n qmxgraph --print-full ==="
        conda devenv -n qmxgraph --print-full
        echo "=== === ==="
        conda devenv -n qmxgraph
        conda install -n qmxgraph coveralls pytest-cov
        conda list -n qmxgraph
        conda init bash
    - name: Tests
      shell: bash -l {0}
      run: |
        conda activate qmxgraph
        scripts/run_tests.sh
    - name: Coveralls
      shell: bash -l {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        conda activate qmxgraph
        coveralls
