name: build

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        #python: ["3.6", "3.7", "3.8", "3.9"]
        python: ["3.6"]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ''
        channels: conda-forge,esss
        channel-priority: true
    - name: Install
      env:
        PYTHON_VERSION: ${{ matrix.python }}
      run: |
        conda config --system --set always_yes yes --set changeps1 no
        conda install -c conda-forge conda-devenv
        conda info -a
        export TEST_QMXGRAPH=1
        conda devenv -n qmxgraph
        conda install -n qmxgraph coveralls pytest-cov
        conda list -n qmxgraph
        conda init bash
    - name: Tests
      shell: bash -l {0}
      run: |
        conda activate qmxgraph
        scripts/run_tests.sh
    - name: Coveralls
      shell: bash -l {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        conda activate qmxgraph
        coveralls
