name: build

on:
  push:
    branches:
      - master

  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.10"]

    steps:
    - uses: actions/checkout@v5
    - uses: browser-actions/setup-chrome@v2.1.0
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
        channels: conda-forge,esss
        channel-priority: true
    - name: Install
      env:
        PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      run: |
        conda config --system --set always_yes yes --set changeps1 no
        conda install -c conda-forge conda-devenv
        conda info -a
        export TEST_QMXGRAPH=1
        conda devenv -n qmxgraph
        conda list -n qmxgraph
    - name: Tests
      shell: bash -l {0}
      run: |
        conda activate qmxgraph
        scripts/run_tests.sh
    - name: Coveralls
      shell: bash -l {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        conda activate qmxgraph
        coveralls
